
GET http://localhost:3001/
###


GET http://localhost:3001/api/persons/
###

GET http://localhost:3001/api/persons/5
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    /// id tulee automaattisesti const generateId() -metodin kautta
    "content": "VS code rest client",
    "important": true
}
###


DELETE http://localhost:3001/api/notes/5
###



